include(":CustomBadges")
include(":BetterChatbox")
include(":BetterChannelIcons")
include(":DN")
include(":Discovery")
include(":FavoriteMessages")
include(":FriendNicknames")
include(":GuildProfiles")
include(":HideCallButtons")
include(":KeywordAlerts")
include(":MessageLinkContext")
include(":MoreHighlight")
include(":RCM")
include(":ShowPerms")
include(":Sessions")
include(":TwemojiEverywhere")
include(":UserTags")
include(":ViewServerAsRole")

rootProject.name = "plugins"
